# Generated by Django 2.2 on 2020-09-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_wall_app', '0003_auto_20200809_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
