# Generated by Django 2.2 on 2020-09-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
